name: Java - Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RECIPIENT_EMAIL: ${{ secrets.TARGET_EMAIL }}

jobs:

  #Execução dos Testes
  tests:
    runs-on: ubuntu-latest
    name: Executar Testes
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Java 23 manualmente
        run: |
            sudo apt-get update
            sudo apt-get install -y wget tar
            wget https://download.java.net/java/early_access/jdk23/6/GPL/openjdk-23-ea+6_linux-x64_bin.tar.gz
            mkdir -p /opt/jdk
            tar -xzf openjdk-23-ea+6_linux-x64_bin.tar.gz -C /opt/jdk
            echo "JAVA_HOME=/opt/jdk/jdk-23" >> $GITHUB_ENV
            echo "/opt/jdk/jdk-23/bin" >> $GITHUB_PATH

      - name: Executar Testes com Maven
        run: mvn test

      - name: Salvar Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/

  #Empacotamento do Projeto
  build:
    runs-on: ubuntu-latest
    name: Build do Projeto
    needs: tests
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Java 23 manualmente
        run: |
            sudo apt-get update
            sudo apt-get install -y wget tar
            wget https://download.java.net/java/early_access/jdk23/6/GPL/openjdk-23-ea+6_linux-x64_bin.tar.gz
            mkdir -p /opt/jdk
            tar -xzf openjdk-23-ea+6_linux-x64_bin.tar.gz -C /opt/jdk
            echo "JAVA_HOME=/opt/jdk/jdk-23" >> $GITHUB_ENV
            echo "/opt/jdk/jdk-23/bin" >> $GITHUB_PATH

      - name: Build do Projeto com Maven
        run: mvn clean package

      - name: Salvar Artefato (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: pacote-jar
          path: target/*.jar

  #Enviar E-mail (em paralelo)
  notify:
    runs-on: ubuntu-latest
    name: Notificação por E-mail
    needs: [tests, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar mailutils
        run: |
          sudo apt update
          sudo apt install -y mailutils

      - name: Enviar E-mail
        run: |
          echo "Pipeline executado com sucesso!" | mail -s "CI/CD - Notificação de Pipeline" $RECIPIENT_EMAIL
