name: Java - Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RECIPIENT_EMAIL: ${{ secrets.TARGET_EMAIL }}

jobs:

  #Execução dos Testes
  tests:
    runs-on: ubuntu-latest
    name: Executar Testes
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Executar Testes com Maven
        run: mvn test

      - name: Salvar Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/

  #Empacotamento do Projeto
  build:
    runs-on: ubuntu-latest
    name: Build do Projeto
    needs: tests
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
            java-version: '23'
            distribution: 'temurin'
            cache: maven

      - name: Build do Projeto com Maven
        run: mvn clean package

      - name: Salvar Artefato (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: pacote-jar
          path: target/*.jar

  #Enviar E-mail (em paralelo)
  notify:
    runs-on: ubuntu-latest
    name: Notificação por E-mail
    needs: [tests, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar mailutils
        run: |
          sudo apt update
          sudo apt install -y mailutils

      - name: Executar script de notificação
        run: |
          chmod +x Actions/shell.sh
          ./Actions/shell.sh
